# Utiliser une image officielle Nginx
FROM nginx:alpine

# Copier les fichiers frontend dans le répertoire Nginx
COPY frontend/ /usr/share/nginx/html

# Exposer le port configuré dans .env
EXPOSE ${WEB_PORT}

# Nginx démarre automatiquement
CMD ["nginx", "-g", "daemon off;"]
