version: '3'

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "${MYSQL_PORT}:3306" 
    volumes:
      - mysql_data:/var/lib/mysql
      - ./bdd:/docker-entrypoint-initdb.d  
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "${PHP_MY_ADMIN_PORT}:80"
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      PORT: ${BACKEND_PORT}
      MYSQL_HOST: mysql
      MYSQL_PORT: ${MYSQL_PORT}  # Utilisez le port personnalisé ici
    ports:
      - "${BACKEND_PORT}:3000"
    networks:
      - app-network
    depends_on:
      - mysql

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "${WEB_PORT}:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
